/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.hospitalsanjose.views;

import autonoma.hospitalsanjose.models.Hospital;
import autonoma.hospitalsanjose.models.Paciente;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Katherin
 */
public class MostrarPacientes extends javax.swing.JDialog {

    private Hospital hospital; 
    private VentanaPrincipal ventanaPrincipal; 
    private ArrayList<Paciente> listaPacientes; 
    
    public MostrarPacientes(java.awt.Frame parent, boolean modal,Hospital hospital,VentanaPrincipal ventanaPrincipal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/hospitalsanjose/images/pacientes.png")).getImage());
        }catch (Exception e){
            System.out.println("El icono no se pudo cargar");
        }
        this.hospital = hospital;
        this.ventanaPrincipal= ventanaPrincipal;
        this.listaPacientes = this.hospital.getListaPacientes(); 
        this.llenarTabla(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePacientes = new javax.swing.JTable();
        btnAgregarPacinete = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnActualizarP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminarP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarNumeroDocumentoP = new javax.swing.JTextField();
<<<<<<< HEAD
        btnVolver1 = new javax.swing.JButton();
        btnAgendarCita = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnMostrarCitas = new javax.swing.JPanel();
=======
        btnVolver = new javax.swing.JButton();
        btnAgregarEnfermedad = new javax.swing.JPanel();
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(107, 142, 35));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 220));
        jLabel1.setText("Pacientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(615, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(250, 240, 230));

        jScrollPane1.setBackground(new java.awt.Color(107, 142, 35));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TablePacientes.setBackground(new java.awt.Color(211, 211, 211));
        TablePacientes.setForeground(new java.awt.Color(250, 240, 230));
        TablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Número Documento", "Edad", "Correo Electrónico", "Telefono", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePacientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablePacientes);
        if (TablePacientes.getColumnModel().getColumnCount() > 0) {
            TablePacientes.getColumnModel().getColumn(3).setResizable(false);
            TablePacientes.getColumnModel().getColumn(5).setResizable(false);
        }

        btnAgregarPacinete.setBackground(new java.awt.Color(196, 222, 246));
        btnAgregarPacinete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarPacinete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPacineteMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Agregar Paciente");

        javax.swing.GroupLayout btnAgregarPacineteLayout = new javax.swing.GroupLayout(btnAgregarPacinete);
        btnAgregarPacinete.setLayout(btnAgregarPacineteLayout);
        btnAgregarPacineteLayout.setHorizontalGroup(
            btnAgregarPacineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPacineteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarPacineteLayout.setVerticalGroup(
            btnAgregarPacineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPacineteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBuscarP.setBackground(new java.awt.Color(196, 222, 246));
        btnBuscarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Buscar");

        javax.swing.GroupLayout btnBuscarPLayout = new javax.swing.GroupLayout(btnBuscarP);
        btnBuscarP.setLayout(btnBuscarPLayout);
        btnBuscarPLayout.setHorizontalGroup(
            btnBuscarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btnBuscarPLayout.setVerticalGroup(
            btnBuscarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarPLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        btnActualizarP.setBackground(new java.awt.Color(196, 222, 246));
        btnActualizarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarPMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Actualizar Paciente");

        javax.swing.GroupLayout btnActualizarPLayout = new javax.swing.GroupLayout(btnActualizarP);
        btnActualizarP.setLayout(btnActualizarPLayout);
        btnActualizarPLayout.setHorizontalGroup(
            btnActualizarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnActualizarPLayout.setVerticalGroup(
            btnActualizarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminarP.setBackground(new java.awt.Color(196, 222, 246));
        btnEliminarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Eliminar Paciente");

        javax.swing.GroupLayout btnEliminarPLayout = new javax.swing.GroupLayout(btnEliminarP);
        btnEliminarP.setLayout(btnEliminarPLayout);
        btnEliminarPLayout.setHorizontalGroup(
            btnEliminarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEliminarPLayout.setVerticalGroup(
            btnEliminarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBuscarNumeroDocumentoP.setForeground(new java.awt.Color(51, 51, 51));

        btnVolver1.setBackground(new java.awt.Color(196, 222, 246));
        btnVolver1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(105, 105, 105));
        btnVolver1.setText("Volver");
        btnVolver1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        btnAgendarCita.setBackground(new java.awt.Color(196, 222, 246));
        btnAgendarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgendarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendarCitaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Agendar Cita");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnAgendarCitaLayout = new javax.swing.GroupLayout(btnAgendarCita);
        btnAgendarCita.setLayout(btnAgendarCitaLayout);
        btnAgendarCitaLayout.setHorizontalGroup(
            btnAgendarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgendarCitaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgendarCitaLayout.setVerticalGroup(
            btnAgendarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgendarCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMostrarCitas.setBackground(new java.awt.Color(196, 222, 246));
        btnMostrarCitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarCitasMouseClicked(evt);
=======
        btnAgregarEnfermedad.setBackground(new java.awt.Color(196, 222, 246));
        btnAgregarEnfermedad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarEnfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarEnfermedadMouseClicked(evt);
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
<<<<<<< HEAD
        jLabel7.setText("Mostrar Citas");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnMostrarCitasLayout = new javax.swing.GroupLayout(btnMostrarCitas);
        btnMostrarCitas.setLayout(btnMostrarCitasLayout);
        btnMostrarCitasLayout.setHorizontalGroup(
            btnMostrarCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarCitasLayout.createSequentialGroup()
=======
        jLabel7.setText("AgregarEnfermedad");

        javax.swing.GroupLayout btnAgregarEnfermedadLayout = new javax.swing.GroupLayout(btnAgregarEnfermedad);
        btnAgregarEnfermedad.setLayout(btnAgregarEnfermedadLayout);
        btnAgregarEnfermedadLayout.setHorizontalGroup(
            btnAgregarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarEnfermedadLayout.createSequentialGroup()
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
<<<<<<< HEAD
        btnMostrarCitasLayout.setVerticalGroup(
            btnMostrarCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
        btnAgregarEnfermedadLayout.setVerticalGroup(
            btnAgregarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarEnfermedadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
<<<<<<< HEAD
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnActualizarP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarPacinete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgendarCita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarCitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtBuscarNumeroDocumentoP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(1058, Short.MAX_VALUE)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
=======
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnActualizarP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarPacinete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtBuscarNumeroDocumentoP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnAgregarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
=======
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
                        .addComponent(btnAgregarPacinete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
<<<<<<< HEAD
                        .addComponent(btnAgendarCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscarNumeroDocumentoP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(588, Short.MAX_VALUE)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
=======
                        .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarNumeroDocumentoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPacineteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPacineteMouseClicked
        AgregarPacientes ventanaAgregarPaciente = new AgregarPacientes(this.ventanaPrincipal,true,hospital,this);
        ventanaAgregarPaciente.setVisible(true);

    }//GEN-LAST:event_btnAgregarPacineteMouseClicked

    private void btnBuscarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPMouseClicked
        String documento = this.txtBuscarNumeroDocumentoP.getText(); 
        Paciente p = this.hospital.buscarPacienteNumDocumento(documento);
        if(p== null){
            JOptionPane.showMessageDialog(this, "el paciente con numero de documento: " + documento + " no se encuentra registrado" );
        }
        else {
            JOptionPane.showMessageDialog(this, "El paciente con numero de documento: "+ documento + " nombre" + p.getNombre() + " se encuentra registrado");
        }
        this.txtBuscarNumeroDocumentoP.setText("");
    }//GEN-LAST:event_btnBuscarPMouseClicked

    private void btnActualizarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPMouseClicked
        int fila = this.TablePacientes.getSelectedRow();
        if (fila >= 0){
            Paciente p = this.listaPacientes.get(fila);
            ActualizarPaciente ventanaActualizarP = new ActualizarPaciente(this.ventanaPrincipal,true,hospital,this,p); 
            ventanaActualizarP.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el paciente que desea actualizar");
        }
    }//GEN-LAST:event_btnActualizarPMouseClicked

    private void btnEliminarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPMouseClicked
        int fila = this.TablePacientes.getSelectedRow();
        if (fila >= 0){
            Paciente p = this.listaPacientes.get(fila);
            int option = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el paciente"+p.getNombre()+ " de forma permanente?");
            if (option == 0){
            this.hospital.eliminarPaciente(p.getId());
            this.listaPacientes=this.hospital.getListaPacientes();
            this.llenarTabla();
            JOptionPane.showMessageDialog(this, "El paciente "+p.getNombre()+" fue eliminado de forma exitosa");
            
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el paciente que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarPMouseClicked

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnAgendarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarCitaMouseClicked
        int fila = this.TablePacientes.getSelectedRow();
        if (fila >= 0){
            Paciente p = this.listaPacientes.get(fila);
            AgregarCita ventanaAgregarCita = new AgregarCita(this.ventanaPrincipal,true,hospital,this,p);
            ventanaAgregarCita.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el paciente al cual desea gendar cita");
        }
        
    }//GEN-LAST:event_btnAgendarCitaMouseClicked

    private void btnMostrarCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarCitasMouseClicked
        MostrarCitas ventanaMostrarCita = new MostrarCitas(this.ventanaPrincipal,true,hospital,this);
        ventanaMostrarCita.setVisible(true);
    }//GEN-LAST:event_btnMostrarCitasMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnAgregarEnfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEnfermedadMouseClicked
        AgregarEnfermedad enfermedadPa = new AgregarEnfermedad (this.ventanaPrincipal,true,hospital,null);
        enfermedadPa.setVisible(true);
    }//GEN-LAST:event_btnAgregarEnfermedadMouseClicked

    
    public void llenarTabla (){
         DefaultTableModel modelDefault = new DefaultTableModel (new String[]{"Nombre","Número Documento", "Edad","Correo Electrónico","Telefono", "Estado"},this.listaPacientes.size());
        this.TablePacientes.setModel(modelDefault); 
        TableModel dataModel = this.TablePacientes.getModel();
        for (int i = 0; i < this.listaPacientes.size(); i++) {
            Paciente paciente = this.listaPacientes.get(i);
            dataModel.setValueAt(paciente.getNombre(),i,0);
            dataModel.setValueAt(paciente.getNumDocumento(),i,1);
            dataModel.setValueAt(paciente.getEdad(),i,2);
            dataModel.setValueAt(paciente.getCorreoElectronico(),i,3);
            dataModel.setValueAt(paciente.getTelefono(),i,4);
            dataModel.setValueAt(paciente.getEstado(),i,5);
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePacientes;
    private javax.swing.JPanel btnActualizarP;
<<<<<<< HEAD
    private javax.swing.JPanel btnAgendarCita;
=======
    private javax.swing.JPanel btnAgregarEnfermedad;
>>>>>>> fd57596d0c7e78d260d4eaf9de0a006824e364ff
    private javax.swing.JPanel btnAgregarPacinete;
    private javax.swing.JPanel btnBuscarP;
    private javax.swing.JPanel btnEliminarP;
    private javax.swing.JPanel btnMostrarCitas;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarNumeroDocumentoP;
    // End of variables declaration//GEN-END:variables
}
