/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.hospitalsanjose.views;

import autonoma.hospitalsanjose.models.Cita;
import autonoma.hospitalsanjose.models.Hospital;
import autonoma.hospitalsanjose.models.Paciente;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Katherin
 */
public class MostrarCitas extends javax.swing.JDialog {

    
    private Hospital hospital; 
    private MostrarPacientes mostrarPacientes; 
    private ArrayList<Cita> listaCitas; 
    
    public MostrarCitas(java.awt.Frame parent, boolean modal,Hospital hospital,MostrarPacientes mostrarPacientes) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/hospitalsanjose/images/pacientes.png")).getImage());
        }catch (Exception e){
            System.out.println("El icono no se pudo cargar");
        }
        this.hospital = hospital;
        this.mostrarPacientes = mostrarPacientes;
        this.listaCitas=this.hospital.getListaCitas();
        this.llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCitas = new javax.swing.JTable();
        txtBuscarM = new javax.swing.JTextField();
        btnActualizarC = new javax.swing.JButton();
        btnEliminarC = new javax.swing.JButton();
        btnBuscarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(107, 142, 35));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 220));
        jLabel1.setText("MOSTRAR CITAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(250, 240, 230));

        jScrollPane1.setBackground(new java.awt.Color(107, 142, 35));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TableCitas.setBackground(new java.awt.Color(211, 211, 211));
        TableCitas.setForeground(new java.awt.Color(250, 240, 230));
        TableCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Paciente", "Medico ", "Fecha Consukta ", "Costo Consulta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCitas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableCitas);

        txtBuscarM.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarM.setForeground(new java.awt.Color(51, 51, 51));

        btnActualizarC.setText("Actualizar Cita");
        btnActualizarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarCMouseClicked(evt);
            }
        });

        btnEliminarC.setText("Eliminar Cita ");
        btnEliminarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCMouseClicked(evt);
            }
        });

        btnBuscarC.setText("Buscar");
        btnBuscarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCMouseClicked(evt);
            }
        });
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(txtBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBuscarC, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(590, 590, 590))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarCMouseClicked
        int fila = this.TableCitas.getSelectedRow();
        if (fila >= 0){
            Cita c = this.listaCitas.get(fila);
            ActualizarCita ventanaActualizarC = new ActualizarCita(null,true,hospital,this,c); 
            ventanaActualizarC.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el paciente que desea actualizar");
        }
    }//GEN-LAST:event_btnActualizarCMouseClicked

    private void btnEliminarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCMouseClicked
        int fila = this.TableCitas.getSelectedRow();
        if (fila >= 0){
            Cita c = this.listaCitas.get(fila);
            int option = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la cita para el paciente:  "+c.getPaciente().getNombre()+ " de forma permanente?");
            if (option == 0){
                this.hospital.eliminarCita(c);
                this.listaCitas=this.hospital.getListaCitas();
                this.llenarTabla();
                JOptionPane.showMessageDialog(this, "El la cita para el paciente:  "+c.getPaciente().getNombre()+" fue eliminada de forma exitosa");

            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione la cita que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarCMouseClicked

    private void btnBuscarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCMouseClicked
        String fechaConsulta = this.txtBuscarM.getText(); 
        Cita c = this.hospital.buscarCitaFechaConsulta(fechaConsulta);
        if(c == null){
            JOptionPane.showMessageDialog(this, "la cita  con fecha de consulta: " + fechaConsulta + " no se encuentra registrada" );
        }
        else {
            JOptionPane.showMessageDialog(this, "El paciente con nombre "+ c.getPaciente().getNombre() +   " tiene una cita asiganda para la fecha : "+ fechaConsulta);
        }
        this.txtBuscarM.setText("");
    }//GEN-LAST:event_btnBuscarCMouseClicked

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public void llenarTabla (){
         DefaultTableModel modelDefault = new DefaultTableModel (new String[]{"Nombre Paciente","Medico", "Fecha Consulta","Costo Consulta"},this.listaCitas.size());
        this.TableCitas.setModel(modelDefault); 
        TableModel dataModel = this.TableCitas.getModel();
        for (int i = 0; i < this.listaCitas.size(); i++) {
            Cita c = this.listaCitas.get(i);
            dataModel.setValueAt(c.getPaciente().getNombre(),i,0);
            dataModel.setValueAt(c.getMedicoConsulta().getNombre(),i,1);
            dataModel.setValueAt(c.getFechaConsulta(),i,2);
            dataModel.setValueAt(c.getValorConsulta(),i,3);       
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCitas;
    private javax.swing.JButton btnActualizarC;
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnEliminarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarM;
    // End of variables declaration//GEN-END:variables
}
