/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.hospitalsanjose.views;

import autonoma.hospitalsanjose.models.Empleado;
import autonoma.hospitalsanjose.models.Hospital;
import autonoma.hospitalsanjose.models.Paciente;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Andres Rodriguez
 */
public class MostrarEmpleados extends javax.swing.JDialog {

    private Hospital hospital; 
    private VentanaPrincipal ventanaPrincipal; 
    private ArrayList<Empleado> listaEmpleados;
    
    public MostrarEmpleados(java.awt.Frame parent, boolean modal,Hospital hospital,VentanaPrincipal ventanaPrincipal) {
        
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/hospitalsanjose/images/hospital.png")).getImage());
        }catch (Exception e){
            System.out.println("no veo la imagen");
        }
        this.hospital = hospital;
        this.ventanaPrincipal= ventanaPrincipal;
        this.listaEmpleados = this.hospital.getNomina().getlistaEmpleados(); 
        this.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEmpleados = new javax.swing.JTable();
        txtBuscarEmpleado = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnAgregarE = new javax.swing.JButton();
        btnActualizarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(107, 142, 35));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 220));
        jLabel1.setText("EMPLEADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(250, 240, 230));

        jScrollPane1.setBackground(new java.awt.Color(107, 142, 35));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TableEmpleados.setBackground(new java.awt.Color(211, 211, 211));
        TableEmpleados.setForeground(new java.awt.Color(51, 51, 51));
        TableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Número Documento", "Edad", "Salario Base", "Especialidad", "Horas Trabajadas", "Area Trabajo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableEmpleados.setSelectionBackground(new java.awt.Color(196, 222, 246));
        TableEmpleados.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TableEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableEmpleados);
        if (TableEmpleados.getColumnModel().getColumnCount() > 0) {
            TableEmpleados.getColumnModel().getColumn(0).setResizable(false);
            TableEmpleados.getColumnModel().getColumn(1).setResizable(false);
            TableEmpleados.getColumnModel().getColumn(2).setResizable(false);
            TableEmpleados.getColumnModel().getColumn(3).setResizable(false);
            TableEmpleados.getColumnModel().getColumn(4).setResizable(false);
        }

        txtBuscarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarEmpleado.setForeground(new java.awt.Color(51, 51, 51));

        btnBuscarE.setBackground(new java.awt.Color(196, 222, 246));
        btnBuscarE.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnBuscarE.setForeground(new java.awt.Color(102, 102, 102));
        btnBuscarE.setText("Buscar");
        btnBuscarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(196, 222, 246));
        btnVolver.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(102, 102, 102));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAgregarE.setBackground(new java.awt.Color(196, 222, 246));
        btnAgregarE.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnAgregarE.setForeground(new java.awt.Color(102, 102, 102));
        btnAgregarE.setText("Agregar Empleado");
        btnAgregarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEActionPerformed(evt);
            }
        });

        btnActualizarE.setBackground(new java.awt.Color(196, 222, 246));
        btnActualizarE.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnActualizarE.setForeground(new java.awt.Color(102, 102, 102));
        btnActualizarE.setText("Actualizar Empleado");
        btnActualizarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEActionPerformed(evt);
            }
        });

        btnEliminarE.setBackground(new java.awt.Color(196, 222, 246));
        btnEliminarE.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnEliminarE.setForeground(new java.awt.Color(102, 102, 102));
        btnEliminarE.setText("Eliminar Empleado");
        btnEliminarE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1068, 1068, 1068)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarE, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnAgregarE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
         String documento = this.txtBuscarEmpleado.getText(); 
        Empleado e = this.hospital.buscarEmpleadoNumDocumento(documento);
        if(e== null){
            JOptionPane.showMessageDialog(this, "el empleado con numero de documento: " + documento + " no se encuentra registrado" );
        }
        else {
            JOptionPane.showMessageDialog(this, "El empleado con numero de documento: "+ documento + " nombre" + e.getNombre() + " se encuentra registrado");
        }
        this.txtBuscarEmpleado.setText("");
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEActionPerformed
        AgregarEmpleado ventanaAgregarEmpleado = new AgregarEmpleado(this.ventanaPrincipal,true,hospital,this);
        ventanaAgregarEmpleado.setVisible(true);
    }//GEN-LAST:event_btnAgregarEActionPerformed

    private void btnActualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEActionPerformed
        int fila = this.TableEmpleados.getSelectedRow();
        if (fila >= 0){
            Empleado e = this.listaEmpleados.get(fila);
            ActualizarEmpleado ventanaActualizarE = new ActualizarEmpleado(this.ventanaPrincipal,true,hospital,this,e); 
            ventanaActualizarE.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el empleado que desea actualizar");
        }
    }//GEN-LAST:event_btnActualizarEActionPerformed

    private void btnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEActionPerformed
        int fila = this.TableEmpleados.getSelectedRow();
        if (fila >= 0){
            Empleado e = this.listaEmpleados.get(fila);
            int option = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el empleado"+e.getNombre()+ " de forma permanente?");
            if (option == 0){
            this.hospital.eliminarEmpleado(e.getId());
            this.listaEmpleados=this.hospital.getNomina().getlistaEmpleados();
            this.llenarTabla();
            JOptionPane.showMessageDialog(this, "El empleado "+e.getNombre()+" fue eliminado de forma exitosa");
            
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el empleado que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarEActionPerformed
    
    public void llenarTabla (){
         DefaultTableModel modelDefault = new DefaultTableModel (new String[]{"Nombre","Número Documento", "Edad","Salario Base","especialidad", "Numero Horas Trabajadas", "Area de Trabajo"},this.listaEmpleados.size());
        this.TableEmpleados.setModel(modelDefault); 
        TableModel dataModel = this.TableEmpleados.getModel();
        for (int i = 0; i < this.listaEmpleados.size(); i++) {
            Empleado e = this.listaEmpleados.get(i);
            
            dataModel.setValueAt(e.getNombre(),i,0);
            dataModel.setValueAt(e.getNumeroDocumento(),i,1);
            dataModel.setValueAt(e.getEdad(),i,2);
            dataModel.setValueAt(e.getSalarioBase(),i,3);
            
        }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableEmpleados;
    private javax.swing.JButton btnActualizarE;
    private javax.swing.JButton btnAgregarE;
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarEmpleado;
    // End of variables declaration//GEN-END:variables
}
