/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.hospitalsanjose.views;

import autonoma.hospitalsanjose.models.Empleado;
import autonoma.hospitalsanjose.models.Hospital;
import autonoma.hospitalsanjose.models.Medicamento;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Katherin
 */
public class MostrarFarmacia extends javax.swing.JDialog {

    private Hospital hospital; 
    private VentanaPrincipal ventanaPrincipal; 
    private ArrayList<Medicamento> listaMedicamentos;
    
    public MostrarFarmacia(java.awt.Frame parent, boolean modal,Hospital hospital,VentanaPrincipal ventanaPrincipal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try {
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/hospitalsanjose/images/hospital.png")).getImage());
        }catch (Exception e){
            System.out.println("no veo la imagen");
        }
        this.hospital = hospital;
        this.ventanaPrincipal= ventanaPrincipal;
        this.listaMedicamentos = this.hospital.getFarmacia().getInventario().getlistaMedicamentos(); 
        this.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFarmacia = new javax.swing.JTable();
        btnMostrarVenta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarM = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnActualizarM = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminarM = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarM = new javax.swing.JTextField();
        btnAgregarMedicamento1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnVenderM = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(107, 142, 35));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 220));
        jLabel1.setText("Farmacia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(250, 240, 230));

        jScrollPane1.setBackground(new java.awt.Color(107, 142, 35));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TableFarmacia.setBackground(new java.awt.Color(211, 211, 211));
        TableFarmacia.setForeground(new java.awt.Color(250, 240, 230));
        TableFarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Costo", "Precio Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableFarmacia.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableFarmacia);

        btnMostrarVenta.setBackground(new java.awt.Color(196, 222, 246));
        btnMostrarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarVentaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Mostrar Ventas");

        javax.swing.GroupLayout btnMostrarVentaLayout = new javax.swing.GroupLayout(btnMostrarVenta);
        btnMostrarVenta.setLayout(btnMostrarVentaLayout);
        btnMostrarVentaLayout.setHorizontalGroup(
            btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        btnMostrarVentaLayout.setVerticalGroup(
            btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBuscarM.setBackground(new java.awt.Color(196, 222, 246));
        btnBuscarM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Buscar");

        javax.swing.GroupLayout btnBuscarMLayout = new javax.swing.GroupLayout(btnBuscarM);
        btnBuscarM.setLayout(btnBuscarMLayout);
        btnBuscarMLayout.setHorizontalGroup(
            btnBuscarMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarMLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btnBuscarMLayout.setVerticalGroup(
            btnBuscarMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnActualizarM.setBackground(new java.awt.Color(196, 222, 246));
        btnActualizarM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Actualizar Medicamento");

        javax.swing.GroupLayout btnActualizarMLayout = new javax.swing.GroupLayout(btnActualizarM);
        btnActualizarM.setLayout(btnActualizarMLayout);
        btnActualizarMLayout.setHorizontalGroup(
            btnActualizarMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnActualizarMLayout.setVerticalGroup(
            btnActualizarMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnActualizarMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        btnEliminarM.setBackground(new java.awt.Color(196, 222, 246));
        btnEliminarM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Eliminar Medicamento");

        javax.swing.GroupLayout btnEliminarMLayout = new javax.swing.GroupLayout(btnEliminarM);
        btnEliminarM.setLayout(btnEliminarMLayout);
        btnEliminarMLayout.setHorizontalGroup(
            btnEliminarMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarMLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        btnEliminarMLayout.setVerticalGroup(
            btnEliminarMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBuscarM.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarM.setForeground(new java.awt.Color(51, 51, 51));

        btnAgregarMedicamento1.setBackground(new java.awt.Color(196, 222, 246));
        btnAgregarMedicamento1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarMedicamento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMedicamento1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Agregar Medicamento");

        javax.swing.GroupLayout btnAgregarMedicamento1Layout = new javax.swing.GroupLayout(btnAgregarMedicamento1);
        btnAgregarMedicamento1.setLayout(btnAgregarMedicamento1Layout);
        btnAgregarMedicamento1Layout.setHorizontalGroup(
            btnAgregarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMedicamento1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarMedicamento1Layout.setVerticalGroup(
            btnAgregarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMedicamento1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVenderM.setBackground(new java.awt.Color(196, 222, 246));
        btnVenderM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVenderM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVenderMMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Vender Medicamento");

        javax.swing.GroupLayout btnVenderMLayout = new javax.swing.GroupLayout(btnVenderM);
        btnVenderM.setLayout(btnVenderMLayout);
        btnVenderMLayout.setHorizontalGroup(
            btnVenderMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVenderMLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnVenderMLayout.setVerticalGroup(
            btnVenderMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVenderMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVenderM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnActualizarM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarMedicamento1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnMostrarVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(txtBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnAgregarMedicamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnEliminarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVenderM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnMostrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentaMouseClicked
        AgregarMedicamento ventanaAgregarMedicamento = new AgregarMedicamento(this.ventanaPrincipal,true,hospital,this);
        ventanaAgregarMedicamento.setVisible(true);

    }//GEN-LAST:event_btnMostrarVentaMouseClicked

    private void btnBuscarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMMouseClicked
        String nombre = this.txtBuscarM.getText();
        Medicamento m = this.hospital.buscarMedicamentoNombre(nombre);
        if(m== null){
            JOptionPane.showMessageDialog(this, "el medicamento con nombre: " + nombre + " no se encuentra registrado" );
        }
        else {
            JOptionPane.showMessageDialog(this, "El medicamento con nombre: "+ nombre + " se encuentra registrado");
        }
        this.txtBuscarM.setText("");
    }//GEN-LAST:event_btnBuscarMMouseClicked

    private void btnActualizarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMMouseClicked
        int fila = this.TableFarmacia.getSelectedRow();
        if (fila >= 0){
            Medicamento m = this.listaMedicamentos.get(fila);
            ActualizarMedicamento ventanaActualizarM = new ActualizarMedicamento(this.ventanaPrincipal,true,hospital,this,m);
            ventanaActualizarM.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el medicamento que desea actualizar");
        }
    }//GEN-LAST:event_btnActualizarMMouseClicked

    private void btnEliminarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMMouseClicked
        int fila = this.TableFarmacia.getSelectedRow();
        if (fila >= 0){
            Medicamento m = this.listaMedicamentos.get(fila);
            int option = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el medicamento "+m.getNombre()+ " de forma permanente?");
            if (option == 0){
                this.hospital.eliminarMedicamento(m.getNombre());
                this.listaMedicamentos=this.hospital.getFarmacia().getInventario().getlistaMedicamentos();
                this.llenarTabla();
                JOptionPane.showMessageDialog(this, "El medicamento "+m.getNombre()+" fue eliminado de forma exitosa");

            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Porfavor seleccione el medicamento que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarMMouseClicked

    private void btnAgregarMedicamento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMedicamento1MouseClicked
        AgregarMedicamento ventanaAgregarMedicamento = new AgregarMedicamento(this.ventanaPrincipal,true,hospital,this);
        ventanaAgregarMedicamento.setVisible(true);
    }//GEN-LAST:event_btnAgregarMedicamento1MouseClicked

    private void btnVenderMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVenderMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenderMMouseClicked

    public void llenarTabla (){
         DefaultTableModel modelDefault = new DefaultTableModel (new String[]{"Nombre","Descripción", "costo","Precio Venta"},this.listaMedicamentos.size());
        this.TableFarmacia.setModel(modelDefault); 
        TableModel dataModel = this.TableFarmacia.getModel();
        for (int i = 0; i < this.listaMedicamentos.size(); i++) {
            Medicamento m = this.listaMedicamentos.get(i);
            
            dataModel.setValueAt(m.getNombre(),i,0);
            dataModel.setValueAt(m.getDescripción(),i,1);
            dataModel.setValueAt(m.getCosto(),i,2);
            dataModel.setValueAt(m.getPrecioVenta(),i,3);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableFarmacia;
    private javax.swing.JPanel btnActualizarM;
    private javax.swing.JPanel btnAgregarMedicamento1;
    private javax.swing.JPanel btnAgregarMedicamento2;
    private javax.swing.JPanel btnBuscarM;
    private javax.swing.JPanel btnEliminarM;
    private javax.swing.JPanel btnMostrarVenta;
    private javax.swing.JPanel btnVenderM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarM;
    // End of variables declaration//GEN-END:variables
}
